config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :consensus
  resources :profits
  resources :latest_dates
  resources :factsheets
  resources :stocks
  resources :sales
  resources :statistics  
  resources :charts, only: [] do
  collection do
    get 'stocks_by_status'
  end
end
  get 'pages/home'

   root 'pages#home'

    get "/list_buy_alert", to: 'sales#list_buy_alert'
    get "/list_sell_alert", to: 'sales#list_sell_alert'
    get "/list_short_sell", to: 'sales#list_short_sell'
    get "/list_cover_buy", to: 'sales#list_cover_buy'
    get "/list_top10_days", to: 'sales#list_top10_days'
    get 'export', to: 'sales#export', as: :sales_export
end

app/models/consensu.rb
class Consensu < ApplicationRecord
	belongs_to :stock
end

app/controllers/consensus_controller.rb
class ConsensusController < ApplicationController
  before_action :set_consensu, only: [:show, :edit, :update, :destroy]

  # GET /consensus
  # GET /consensus.json
  def index
    @consensus = Consensu.all
  end

  # GET /consensus/1
  # GET /consensus/1.json
  def show
  end

  # GET /consensus/new
  def new
    @consensu = Consensu.new
  end

  # GET /consensus/1/edit
  def edit
  end

  # POST /consensus
  # POST /consensus.json
  def create
    @consensu = Consensu.new(consensu_params)

    respond_to do |format|
      if @consensu.save
        format.html { redirect_to @consensu, notice: 'Consensu was successfully created.' }
        format.json { render :show, status: :created, location: @consensu }
      else
        format.html { render :new }
        format.json { render json: @consensu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consensus/1
  # PATCH/PUT /consensus/1.json
  def update
    respond_to do |format|
      if @consensu.update(consensu_params)
        format.html { redirect_to @consensu, notice: 'Consensu was successfully updated.' }
        format.json { render :show, status: :ok, location: @consensu }
      else
        format.html { render :edit }
        format.json { render json: @consensu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consensus/1
  # DELETE /consensus/1.json
  def destroy
    @consensu.destroy
    respond_to do |format|
      format.html { redirect_to consensus_url, notice: 'Consensu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consensu
      @consensu = Consensu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consensu_params
      params.require(:consensu).permit(:name, :price, :buy, :hold, :sell, :eps_a, :eps_b, :pe, :pbv, :yield, :target_price, :status)
    end
end

app/helpers/consensus_helper.rb
module ConsensusHelper
end

app/views/consensus/_form.html.erb
<%= form_for(consensu) do |f| %>
  <% if consensu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consensu.errors.count, "error") %> prohibited this consensu from being saved:</h2>

      <ul>
      <% consensu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :buy %>
    <%= f.number_field :buy %>
  </div>

  <div class="field">
    <%= f.label :hold %>
    <%= f.number_field :hold %>
  </div>

  <div class="field">
    <%= f.label :sell %>
    <%= f.number_field :sell %>
  </div>

  <div class="field">
    <%= f.label :eps_a %>
    <%= f.text_field :eps_a %>
  </div>

  <div class="field">
    <%= f.label :eps_b %>
    <%= f.text_field :eps_b %>
  </div>

  <div class="field">
    <%= f.label :pe %>
    <%= f.text_field :pe %>
  </div>

  <div class="field">
    <%= f.label :pbv %>
    <%= f.text_field :pbv %>
  </div>

  <div class="field">
    <%= f.label :yield %>
    <%= f.text_field :yield %>
  </div>

  <div class="field">
    <%= f.label :target_price %>
    <%= f.text_field :target_price %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consensus/edit.html.erb
<h1>Editing Consensu</h1>

<%= render 'form', consensu: @consensu %>

<%= link_to 'Show', @consensu %> |
<%= link_to 'Back', consensus_path %>

app/views/consensus/index.html.erb
<% content_for :title, 'Consensus' %>

<p id="notice"><%= notice %></p>

<h1>Consensus</h1>

<table id="consensus" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Cons. price</th>
      <th>Pct</th>            
      <th>Buy</th>
      <th>Hold</th>
      <th>Sell</th>
      <th>Ttl</th>
      <th>Eps -A-</th>
      <th>Eps -B-</th>
      <th>Pe</th>
      <th>Pbv</th>
      <th>Yield</th>

      <th>Status</th>
 
    </tr>
  </thead>

  <tbody>
    <% @consensus.each do |consensu| %>

      <tr>
        <td><%= consensu.name %></td>
        <td><%= number_with_precision(consensu.price,
        precision: 2) %></td>
        <td><%= number_with_precision(consensu.consensus_price,
        precision: 2) %></td>
        <td><%= number_with_precision(
        (consensu.consensus_price-consensu.price)/consensu.price*100, 
        precision: 2) %></td>                
        <td><%= consensu.buy %></td>
        <td><%= consensu.hold %></td>
        <td><%= consensu.sell %></td>
        <td><%= (consensu.buy*2) + consensu.hold - (consensu.sell*2) %></td>        
        <td><%= consensu.eps_a %></td>
        <td><%= consensu.eps_b %></td>
        <td><%= consensu.pe %></td>
        <td><%= consensu.pbv %></td>
        <td><%= consensu.yield %></td>

        <%# <td><%= status_desc(consensu.status)</td> %>
        <td><%= consensu.status %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consensu', new_consensu_path %>

app/views/consensus/new.html.erb
<h1>New Consensu</h1>

<%= render 'form', consensu: @consensu %>

<%= link_to 'Back', consensus_path %>

app/views/consensus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @consensu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @consensu.price %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @consensu.buy %>
</p>

<p>
  <strong>Hold:</strong>
  <%= @consensu.hold %>
</p>

<p>
  <strong>Sell:</strong>
  <%= @consensu.sell %>
</p>

<p>
  <strong>Eps a:</strong>
  <%= @consensu.eps_a %>
</p>

<p>
  <strong>Eps b:</strong>
  <%= @consensu.eps_b %>
</p>

<p>
  <strong>Pe:</strong>
  <%= @consensu.pe %>
</p>

<p>
  <strong>Pbv:</strong>
  <%= @consensu.pbv %>
</p>

<p>
  <strong>Yield:</strong>
  <%= @consensu.yield %>
</p>

<p>
  <strong>Target price:</strong>
  <%= @consensu.target_price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @consensu.status %>
</p>

<%= link_to 'Edit', edit_consensu_path(@consensu) %> |
<%= link_to 'Back', consensus_path %>