config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :consensus
  resources :profits
  resources :latest_dates
  resources :factsheets
  resources :stocks
  resources :sales
  resources :statistics  
  resources :charts, only: [] do
  collection do
    get 'stocks_by_status'
  end
end
  get 'pages/home'

   root 'pages#home'

    get "/list_buy_alert", to: 'sales#list_buy_alert'
    get "/list_sell_alert", to: 'sales#list_sell_alert'
    get "/list_short_sell", to: 'sales#list_short_sell'
    get "/list_cover_buy", to: 'sales#list_cover_buy'
    get "/list_top10_days", to: 'sales#list_top10_days'
    get 'export', to: 'sales#export', as: :sales_export
end

app/models/factsheet.rb
class Factsheet < ActiveRecord::Base
  belongs_to :item
end

app/controllers/factsheets_controller.rb
class FactsheetsController < ApplicationController
  before_action :set_factsheet, only: [:show, :edit, :update, :destroy]

  # GET /factsheets
  # GET /factsheets.json
  def index
    @factsheets = Factsheet.where('item_id > 2').includes(:item)
  end

  # GET /factsheets/1
  # GET /factsheets/1.json
  def show
  end

  # GET /factsheets/new
  def new
    @factsheet = Factsheet.new
  end

  # GET /factsheets/1/edit
  def edit
  end

  # POST /factsheets
  # POST /factsheets.json
  def create
    @factsheet = Factsheet.new(factsheet_params)

    respond_to do |format|
      if @factsheet.save
        format.html { redirect_to @factsheet, notice: 'Factsheet was successfully created.' }
        format.json { render :show, status: :created, location: @factsheet }
      else
        format.html { render :new }
        format.json { render json: @factsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factsheets/1
  # PATCH/PUT /factsheets/1.json
  def update
    respond_to do |format|
      if @factsheet.update(factsheet_params)
        format.html { redirect_to @factsheet, notice: 'Factsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @factsheet }
      else
        format.html { render :edit }
        format.json { render json: @factsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factsheets/1
  # DELETE /factsheets/1.json
  def destroy
    @factsheet.destroy
    respond_to do |format|
      format.html { redirect_to factsheets_url, notice: 'Factsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factsheet
      @factsheet = Factsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factsheet_params
      params.require(:factsheet).permit(:name, :item_id, :figure1, :figure2, :figure3, :figure4)
    end
end

app/helpers/factsheets_helper.rb
module FactsheetsHelper
	def growth(nbr1, nbr2)
		growth = ((nbr1 - nbr2)/nbr2 * 100)
		if (nbr2 < 0)
			growth = growth * -1
		end
		return growth
	end
end

app/views/factsheets/_form.html.erb
<%= form_for(@factsheet) do |f| %>
  <% if @factsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factsheet.errors.count, "error") %> prohibited this factsheet from being saved:</h2>

      <ul>
      <% @factsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :item %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :figure1 %><br>
    <%= f.text_field :figure1 %>
  </div>
  <div class="field">
    <%= f.label :figure2 %><br>
    <%= f.text_field :figure2 %>
  </div>
  <div class="field">
    <%= f.label :figure3 %><br>
    <%= f.text_field :figure3 %>
  </div>
  <div class="field">
    <%= f.label :figure4 %><br>
    <%= f.text_field :figure4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factsheets/edit.html.erb
<h1>Editing Factsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @factsheet %> |
<%= link_to 'Back', factsheets_path %>

app/views/factsheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Factsheets</h1>

<table id="factsheets" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Description</th>
      <th>Growth</th>
      <th>Figure1</th>
      <th>Figure2</th>
      <th>Figure3</th>
      <th>Figure4</th>
    </tr>
  </thead>

  <tbody>
    <% @factsheets.each do |factsheet| %>
      <tr>
        <td><%= factsheet.name %></td>
        <td><%= factsheet.item_id %></td>
        <td><%= factsheet.item.desc_en %></td>
        <td><%= number_with_precision(growth(factsheet.figure1, factsheet.figure2), precision: 2, delimiter: ",") %></td>
        <td><%= number_with_precision(factsheet.figure1, precision: 2, delimiter: ",") %></td>
        <td><%= number_with_precision(factsheet.figure2, precision: 2, delimiter: ",") %></td>
        <td><%= number_with_precision(factsheet.figure3, precision: 2, delimiter: ",") %></td>
        <td><%= number_with_precision(factsheet.figure4, precision: 2, delimiter: ",") %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factsheet', new_factsheet_path %>

app/views/factsheets/new.html.erb
<h1>New Factsheet</h1>

<%= render 'form' %>

<%= link_to 'Back', factsheets_path %>

app/views/factsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @factsheet.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @factsheet.item_id %>
</p>

<p>
  <strong>Figure1:</strong>
  <%= @factsheet.figure1 %>
</p>

<p>
  <strong>Figure2:</strong>
  <%= @factsheet.figure2 %>
</p>

<p>
  <strong>Figure3:</strong>
  <%= @factsheet.figure3 %>
</p>

<p>
  <strong>Figure4:</strong>
  <%= @factsheet.figure4 %>
</p>

<%= link_to 'Edit', edit_factsheet_path(@factsheet) %> |
<%= link_to 'Back', factsheets_path %>