config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :consensus
  resources :profits
  resources :latest_dates
  resources :factsheets
  resources :stocks
  resources :sales
  resources :statistics  
  resources :charts, only: [] do
  collection do
    get 'stocks_by_status'
  end
end
  get 'pages/home'

   root 'pages#home'

    get "/list_buy_alert", to: 'sales#list_buy_alert'
    get "/list_sell_alert", to: 'sales#list_sell_alert'
    get "/list_short_sell", to: 'sales#list_short_sell'
    get "/list_cover_buy", to: 'sales#list_cover_buy'
    get "/list_top10_days", to: 'sales#list_top10_days'
    get 'export', to: 'sales#export', as: :sales_export
end

app/models/sale.rb
class Sale < ActiveRecord::Base
    belongs_to :latest_date
    validates_uniqueness_of :name, scope: [:fm_date, :to_date]
   
	default_scope { order('name ASC, fm_date DESC')}

    scope :buy_alert, -> {
        joins(:latest_date).
        where("to_date = date")
    }

    scope :sell_alert, -> {
        joins(:latest_date).        
        where("to_date = date")
    }

    scope :short_sell, -> {
        joins(:latest_date).        
        where("to_date = date")
    }
    scope :cover_buy, -> {
        joins(:latest_date).        
        where("to_date = date")
    }

	before_save :assign_values

    def self.to_csv(attributes = column_names, options = {})
        CSV.generate(options) do |csv|
            attributes = %w(name fm_date to_date fm_price to_price qty max_price min_price)
            csv.add_row attributes
            all.each do |sale|
                values = sale.attributes.slice(*attributes).values
                csv.add_row values
            end
        end
    end
	
	def num_of_spread(minp,maxp)
		div = 0.0
		gap = 0.0
		spd = 0

		if (maxp > minp) 
			gap = maxp - minp
			mult = 1
		else
			tmpp = minp
			minp = maxp
			maxp = tmpp
			gap  = maxp - minp
			mult = -1
		end

		if gap != 0
			case maxp
				when 0.00..2.00 then 
				begin
					div = 0.01 
					spd = gap/div
				end
				when 2.02..5.00 then 
				begin
					div = 0.02
					if minp < (div * 100)
						spd = ((div * 100) - minp) / 0.01
						spd += (maxp - (div * 100)) / div
					else
						spd = gap/div
					end
				end      
				when 5.05..10.00 then  
				begin
					div = 0.05
					if minp < (div * 100)
						spd = ((div * 100) - minp) / 0.02
						spd += (maxp - (div * 100)) / div
					else
						spd = gap/div
					end            
				end      
				when 10.10..25.00 then 
				begin
					div = 0.10
					if minp < (div * 100)
						spd = ((div * 100) - minp) / 0.05
						spd += (maxp - (div * 100)) / div
					else
						spd = gap/div
					end          
				end   
				when 25.25..100.00 then 
				begin
					div = 0.25
					if minp < (div * 100)
						spd = ((div * 100) - minp) / 0.10
						spd += (maxp - (div * 100)) / div
					else
						spd = gap/div
					end            
				end    
				when 100.50..200.00 then 
				begin
					div = 0.50
					if minp < (div * 100)
						spd = ((div * 100) - minp) / 0.25
						spd += (maxp - (div * 100)) / div
					else
						spd = gap/div
					end             
				end      
				when 201.00..400.00 then 
				begin
					div = 1.00
					if minp < (div * 200)
						spd = ((div * 200) - minp) / 0.50
						spd += (maxp - (div * 200)) / div
					else
						spd = gap/div
					end            
				end   
				else 
				begin
					div = 2.00
					if minp < (div * 200)
						spd = ((div * 200) - minp) / 1.00
						spd += (maxp - (div * 200)) / div
					else
						spd = gap/div
					end            
				end         
		end	
		end
		return spd * mult
	end

	def assign_values
		# days
		self.days = 0
		d1 = self.fm_date
		d2 = self.to_date

		while (d1 < d2)
			d1 = d1 + 1
			if d1.cwday < 6
				self.days = self.days + 1
			end
		end

		# diff
		self.diff = self.to_price - self.fm_price
		self.pct = self.diff/self.fm_price*100
		self.ttl_spread = num_of_spread(self.fm_price,self.to_price)
		
        if self.days != 0
		  	self.avg_spread = (self.ttl_spread / self.days).round
        else
            self.avg_spread = 0
        end

        if (self.to_price > self.max_price)
            self.max_price = self.to_price
        end
        if (self.to_price < self.min_price)
            self.min_price = self.to_price
        end        
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all.includes(:latest_date)

  end

  def list_top10_days
    @sales = Sale.find_each
  end

  def list_today
    @q = Sale.ransack(params[:q])
    @sales = @q.result

  end

  def list_buy_alert
    @sales = Sale.buy_alert.includes(:latest_date)
  end

  def list_sell_alert
    @sales = Sale.sell_alert.includes(:latest_date)
  end  

  def list_short_sell
    @sales = Sale.short_sell.includes(:latest_date)
  end 

  def list_cover_buy
    @sales = Sale.cover_buy.includes(:latest_date)
  end 

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def export
  attributes_to_include = %w(name fm_date to_date)
  @data = Sale.where(to_date: '2016-06-03')
  respond_to do |format|
    format.html { redirect_to root_url }
    format.csv { send_data @data.to_csv }
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name, :fm_date, :to_date, :days, :fm_price, :to_price,
       :diff, :pct, :ttl_spread, :avg_spread, :qty, :max_price, :min_price)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- row 1 -->
<div class="row">
  <div class="col-xs-12">    
    <label class="control-label col-xs-2"><%= f.label :name %></label>
    <%= f.text_field :name %>
  </div>
</div>
  <!-- row 2 -->
<div class="row">
  <div class="col-xs-6">    
    <label class="control-label col-xs-4"><%= f.label :fm_date %></label>
    <%= f.date_select :fm_date %>
  </div>
  <div class="col-xs-6">
    <label class="control-label col-xs-4"><%= f.label :to_date %></label>
    <%= f.date_select :to_date %>
  </div>       
</div>
  <!-- row 3 -->
<div class="row">
  <div class="col-xs-6">    
    <label class="control-label col-xs-4"><%= f.label :fm_price %></label>
    <%= f.text_field :fm_price %>
  </div>
  <div class="col-xs-6">
    <label class="control-label col-xs-4"><%= f.label :to_price %></label>
    <%= f.text_field :to_price %>
  </div>       
</div>
  <!-- row 4 -->
<div class="row">
  <div class="col-xs-12">    
    <label class="control-label col-xs-2"><%= f.label :qty %></label>
    <%= f.number_field :qty %>
  </div>
</div>
   
  <!-- row 5 -->
<div class="row">
  <div class="col-xs-6">    
    <label class="control-label col-xs-4"><%= f.label :max_price %></label>
    <%= f.text_field :max_price %>
  </div>
  <div class="col-xs-6">
    <label class="control-label col-xs-4"><%= f.label :min_price %></label>
    <%= f.text_field :min_price %>
  </div>       
</div>   
  <!-- row 6 -->
<div class="row">
  <div class="col-xs-12">    
    <label class="control-label col-xs-2"></label>
    <%= f.submit %>
  </div>
</div>

<% end %>

app/views/sales/edit.html.erb
<div class ="page-header text-center" > 
  <%= link_to 'Back', sales_path, :class => "btn btn-success pull-left"  %>
  <h1><%= "Edit Sales" %></h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<% content_for :title, 'Sales' %>

<p id="notice"><%= notice %></p>

<div class ="page-header text-center" > 
<%= link_to 'Export Data', sales_export_path(format: "csv"),
  :class => "btn btn-success pull-left"  %>
  <h1><%= "Sales" %></h1>
</div>

<table id="sales" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>From date</th>
      <th>To date</th>
      <th>From price</th>
      <th>To price</th>
      <th>Ttl spd</th>
      <th>Days</th>
      <th>Qty</th>
      <th>Max</th>
      <th>Min</th>      
      <th>Pct</th>      
    
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>

      <tr>
        <td><%= sale.name %></td>
        <td><%= sale.fm_date %></td>
        <td><%= sale.to_date %></td>
        <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.to_price, precision: 2) %></td>

        <td><%= sale.ttl_spread %></td>
        <td><%= sale.days %></td>        
        <td><%= number_with_precision(sale.qty, precision: 0,delimiter: ',') %></td>
        <td><%= number_with_precision(sale.max_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.min_price, precision: 2) %></td>    
        <td><%= number_with_precision((sale.to_price-sale.fm_price)/sale.fm_price*100, precision: 2) %></td>    

      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/list_buy_alert.html.erb
<% content_for :title, 'Buy Alert' %>

<p id="notice"><%= notice %></p>

<div class ="page-header text-left" > 
  <h1><%= "Buy Alert" %></h1>
</div>

<table  id="buy_alert" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>D</th> 
      <th>Target</th>
      <th>Qty</th>    
      <th>From date</th>
      <th>To date</th>
      <th>Reason</th>      
      <th>From price</th>
      <th>To price</th>
      <th>Ttl spd</th>
      <th>Stk spd</th> 
      <th>Min</th>      
      <th>Min 52W</th>
      <th>Cons. Price</th>  
      <th>%</th>     
      <th>M</th>     
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
    <% stock = Stock.find_by_name(sale.name) %>
    <% if stock %>
      <% if (stock.status == 'B' || stock.status == 'O') %>
        <%# target = targetted(sale.fm_price*(100+stock.buy_percent)/100) %>
        <% if (stock.buy_target > 0) %>
          <% method = 'T' %>
          <% target = stock.buy_target %>
          <%# <% if (sale.min_price < target) %>
            <%# <% target = sale.min_price %> 
          <%# <% end %>            
        <% else %>
          <% method = 'S' %>        
          <% target = goal(sale.fm_price,stock.buy_spread) %>
          <% if (sale.min_price < target) %>
            <% target = sale.min_price %>
            <% method = 'M' %>        
          <% end %>
        <% end %>    
        <% spreads = num_of_spread(sale.to_price,target).to_i %>
        <%# <% if spreads >= -10 %>    
        <%# if sale.to_price <= sale.fm_price %> 

        <tr>
          <td><%= sale.name %></td>
          <td><%= num_of_spread(sale.to_price,target).round(0).to_i %></td>
          <td><%= number_with_precision(target, precision: 2) %></td>
          <td><%= number_with_delimiter(stock.qty, delimiter: ",") %></td>
  
          <td><%= sale.fm_date.strftime("%b %d") %></td>
          <td><%= sale.to_date.strftime("%b %d") %></td>
          <%# <td><%= sale.days </td> %>
          <td><%= stock.reason %></td>  

          <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
          <td><%= number_with_precision(sale.to_price, precision: 2) %></td>

          <%#= number_with_precision(sale.diff, precision: 2) %>
          <%#= number_with_precision(sale.pct, precision: 2) %>
          <td><%= sale.ttl_spread %></td>
          <%# <% if stock %> 
          <td><%= stock.buy_spread %></td>
          <%# end %>

          <td><%= number_with_precision(sale.min_price, precision: 2) %></td>        
          <td><%= number_with_precision(stock.min_price, precision: 2) %></td>
          <% if stock.consensu %>
            <td><%= number_with_precision(stock.consensu.consensus_price, precision: 2) %></td> 
            <td><%= number_with_precision((stock.consensu.consensus_price-target)/target*100, precision: 0) %></td> 
          <% else %>
            <td><%= 0.00 %></td>  
            <td><%= 0 %></td>            
          <% end %>   
          <td><%= method %></td>             
        </tr>

      <%# end %> <!-- to price < fm price --> 
      <%# <% end %> <!-- spreads <= 10 --> 
      <% end %>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/sales/list_cover_buy.html.erb
<p id="notice"><%= notice %></p>

<div class ="page-header text-left" > 
  <h1><%= "Cover Buy" %></h1>
</div>

<table  id="cover_buy" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>D</th> 
      <th>Target</th>
      <th>Qty</th> 
      <th>Cost</th>            
 
      <th>From date</th>
      <th>To date</th>
      <th>From price</th>
      <th>To price</th>

      <th>Ttl spd</th>
      <th>Stock</th> 
      <th>Min</th>      
      <th>Min 52</th>
      <th>Cons. Price</th>  
      <th>%</th>       
      <th>M</th>      
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <% stock = Stock.find_by_name(sale.name) %>
      <% if (stock.status == 'S' && sale.to_price < sale.fm_price) %>
        <% if (stock.buy_target > 0) %>
          <% target = stock.buy_target %>
          <% method = 'T' %>
        <% else %>
          <% target = goal(sale.fm_price,stock.buy_spread) %>
          <% method = 'S' %>          
        <% end %>  

        <% if (sale.min_price < target) %>
          <% target = sale.min_price %>
          <% method = 'M' %>            
        <% end %>
        <% spreads = num_of_spread(sale.to_price,target).to_i %>
        <%# if spreads >= -10 %> 
        <tr>
          <td><%= sale.name %></td>
          <td><%= num_of_spread(sale.to_price,target).to_i %></td>
          <td><%= number_with_precision(target, precision: 2) %></td>
          <td><%= number_with_delimiter(stock.qty, delimiter: ",") %></td>
          <td><%= number_with_precision(stock.cost, precision: 2) %></td>        

          <td><%= sale.fm_date.strftime("%b %d") %></td>
          <td><%= sale.to_date.strftime("%b %d") %></td>
          <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
          <td><%= number_with_precision(sale.to_price, precision: 2) %></td>

          <td><%= sale.ttl_spread %></td>
          <td><%= stock.buy_spread %></td>          
          <td><%= number_with_precision(sale.min_price, precision: 2) %></td>        
          <td><%= number_with_precision(stock.min_price, precision: 2) %></td>
        <% if stock.consensu %>
          <td><%= number_with_precision(stock.consensu.consensus_price, precision: 2) %></td> 
          <td><%= number_with_precision((stock.consensu.consensus_price-target)/target*100, precision: 0) %></td> 
        <% else %>
          <td><%= 0.00 %></td>  
          <td><%= 0 %></td>            
        <% end %>           
          <td><%= method %></td>                
        </tr>
        <%# end %>   <!-- END OF SPREAD -->     
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/sales/list_short_sell.html.erb
<p id="notice"><%= notice %></p>

<div class ="page-header text-left" > 
  <h1><%= "Short Sell" %></h1>
</div>

<table  id="short_sell" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>D</th>   
      <th>Target</th>
      <th>Qty</th>  
      <th>Cost</th>  
  
      <th>From date</th>
      <th>To date</th>
      <th>From price</th>
      <th>To price</th>
 
      <th>Ttl spd</th>
      <th>Stock</th>
      <th>Max</th>
      <th>Max 52</th>    
      <th>Cons. Price</th>   
      <th>%</th>      
      <th>M</th>        
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <% stock = Stock.find_by_name(sale.name) %>
      <%# if (stock.status == 'S' && stock.sell_target != stock.cost) %>
      <%# if (stock.status == 'S' && stock.available_qty > 0 && sale.to_price >= sale.fm_price) %> 
      <% if stock.status == 'S' && stock.available_qty > 0 %>         

        <% if (stock.sell_target > 0) %>
          <% target = stock.sell_target %>
          <% method = 'T' %>           
        <% else %>        
          <% target = goal(sale.fm_price,stock.sell_spread) %>
          <% method = 'S' %>
          <% if (target < sale.max_price) %>
            <% target = sale.max_price %>
            <% method = 'M' %>          
          <% end %>    
        <% end %> 
        <% spreads = num_of_spread(sale.to_price,target).to_i %>
        <%# if spreads <= 10 %> 
        <tr>
          <td><%= sale.name %></td>
          <td><%= num_of_spread(sale.to_price,target).to_i %></td>
          <td><%= number_with_precision(target, precision: 2) %></td>
          <td><%= number_with_delimiter(stock.qty, delimiter: ",") %></td>
          <td><%= number_with_precision(stock.cost, precision: 2) %></td>        
  
          <td><%= sale.fm_date.strftime("%b %d") %></td>
          <td><%= sale.to_date.strftime("%b %d") %></td>
          <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
          <td><%= number_with_precision(sale.to_price, precision: 2) %></td>
          <td><%= sale.ttl_spread %></td>
          <td><%= stock.sell_spread %></td>
          <td><%= number_with_precision(sale.max_price, precision: 2) %></td>
          <td><%= number_with_precision(stock.max_price, precision: 2) %></td>  
        <% if stock.consensu %>
          <td><%= number_with_precision(stock.consensu.consensus_price, precision: 2) %></td>  
          <td><%= number_with_precision((stock.consensu.consensus_price-target)/target*100, precision: 0) %></td> 
        <% else %>
          <td><%= 0.00 %></td>  
          <td><%= 0 %></td>            
        <% end %>          
          <td><%= method %></td>                
        </tr>
        <%# end %>  <!-- END OF SPREAD -->
      <% end %>  
    <% end %>
  </tbody>
</table>

app/views/sales/list_today.html.erb
<p id="notice"><%= notice %></p>

<div class ="page-header text-center" > 
  <%= link_to 'New Sale', new_sale_path,
  :class => "btn btn-success pull-right"  %>
  <h1><%= "Today Sales" %></h1>
</div>

<%= search_form_for @q do |f| %>
  <div class="field">
    <%= f.label :to_date_eq, "To date eq " %>
    <%= f.text_field :to_date_eq %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>From date</th>
      <th>To date</th>
      <th>From price</th>
      <th>To price</th>
      <th>Diff.</th>
      <th>Pct.</th>
      <th>Ttl spd</th>
      <th>Days</th>
      <th>Avg spd</th>
      <th>Qty</th>
      <th>Max</th>
      <th>Min</th>      
      <th></th>
      <th></th>     
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.name %></td>
        <td><%= link_to_icon 'Edit', edit_sale_path(sale) %></td>   
        <td><%= sale.fm_date %></td>
        <td><%= sale.to_date %></td>
        <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.to_price, precision: 2) %></td>

        <td><%= number_with_precision(sale.diff, precision: 2) %></td>
        <td><%= number_with_precision(sale.pct, precision: 2) %></td>
        <td><%= sale.ttl_spread %></td>
        <td><%= sale.days %></td>        
        <td><%= sale.avg_spread %></td>
        <td><%= number_with_precision(sale.qty, precision: 0,delimiter: ',') %></td>
        <td><%= number_with_precision(sale.max_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.min_price, precision: 2) %></td>        
        <td><%= link_to_icon 'Show', sale %></td>
        <td><%= link_to_icon 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/list_top10_days.html.erb
<p id="notice"><%= notice %></p>

<div class ="page-header text-center" > 
  <%= link_to 'New Sale', new_sale_path,
  :class => "btn btn-success pull-right"  %>
  <h1><%= "Top 10 Days" %></h1>
</div>

<table id="sales" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>From date</th>
      <th>To date</th>
      <th>From price</th>
      <th>To price</th>
      <th>Diff.</th>
      <th>Stock</th>
      <th>Ttl spd</th>
      <th>Days</th>
      <th>Avg spd</th>
      <th>Qty</th>
      <th>Max</th>
      <th>Min</th>      
      <th></th>
      <th></th>     
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
    <% stock = Stock.find_by_name(sale.name) %>

      <tr>
        <td><%= sale.name %></td>
        <td><%= link_to_icon 'Edit', edit_sale_path(sale) %></td>   
        <td><%= sale.fm_date %></td>
        <td><%= sale.to_date %></td>
        <td><%= number_with_precision(sale.fm_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.to_price, precision: 2) %></td>

        <td><%= number_with_precision(sale.diff, precision: 2) %></td>
        <td><%= link_to 'Stk', edit_stock_path(stock.id, :param1 => sale.ttl_spread) %></td>
        <td><%= sale.ttl_spread %></td>
        <td><%= sale.days %></td>        
        <td><%= sale.avg_spread %></td>
        <td><%= number_with_precision(sale.qty, precision: 0,delimiter: ',') %></td>
        <td><%= number_with_precision(sale.max_price, precision: 2) %></td>
        <td><%= number_with_precision(sale.min_price, precision: 2) %></td>        
        <td><%= link_to_icon 'Show', sale %></td>
        <td><%= link_to_icon 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<div class ="page-header text-center" > 
  <%= link_to 'Back', sales_path,
  :class => "btn btn-success pull-left"  %>
  <h1><%= "New Sales" %></h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<% if notice %>
  <div class="alert alert-info">
    <p id="notice">
      <%= notice %>
    </div>
  </div>
<% end %>
<br/>
<div class ="page-header text-center" > 
  <%= link_to 'Back', sales_path,
  :class => "btn btn-success pull-right"  %>
  <h1><%= "New Sales" %></h1>
</div>
<!-- row 1 -->
<div class="row">
  <div class="col-xs-12">    
    <label class="control-label col-xs-6">Name:</label>
    <%= @sale.name %>
  </div>
</div>
<!-- row 2 -->
<div class="row">
  <div class="col-xs-4">    
    <label class="control-label col-xs-6">Fm date:</label>
    <%= @sale.fm_date %>
  </div>
  <div class="col-xs-4">
    <label class="control-label col-xs-6">To date:</label>
    <%= @sale.to_date %>
  </div>
  <div class="col-xs-4">
      <label class="control-label col-xs-8">Days:</label>
      <%= @sale.days %>
  </div>        
</div>
<!-- row 3 -->
<div class="row">
  <div class="col-xs-4">    
    <label class="control-label col-xs-6">Fm price:</label>
  <%= @sale.fm_price %>
  </div>
  <div class="col-xs-4">
    <label class="control-label col-xs-6">To price:</label>
  <%= @sale.to_price %>
  </div>
  <div class="col-xs-4">
      <label class="control-label col-xs-8">Diff:</label>
  <%= @sale.diff %>
  </div>        
</div>
<!-- row 4 -->
<div class="row">
  <div class="col-xs-4">    
    <label class="control-label col-xs-6">Pct:</label>
  <%= @sale.pct %>
  </div>
  <div class="col-xs-4">
    <label class="control-label col-xs-6">Ttl spread:</label>
  <%= @sale.ttl_spread %>
  </div>
  <div class="col-xs-4">
      <label class="control-label col-xs-8">Avg spread:</label>
  <%= @sale.avg_spread %>
  </div>        
</div>
<!-- row 5 -->
<div class="row">
  <div class="col-xs-4">    
    <label class="control-label col-xs-6">Qty:</label>
  <%= @sale.qty %>
  </div>
  <div class="col-xs-4">
    <label class="control-label col-xs-6">Max price:</label>
  <%= @sale.max_price %>
  </div>
  <div class="col-xs-4">
      <label class="control-label col-xs-8">Min price:</label>
  <%= @sale.min_price %>
  </div>        
</div>
<!-- row 6 -->
<div class="row">
  <div class="col-xs-6">    
    <label class="control-label col-xs-6"></label>
  <%= link_to 'Edit', edit_sale_path(@sale), 
        :class => " btn btn-warning btn-xs active" %>
  </div>
  <div class="col-xs-6">
    <label class="control-label col-xs-6"></label>
  <%= link_to 'Back', sales_path, 
        :class => " btn btn-info btn-xs active" %>
  </div>
       
</div>