config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :consensus
  resources :profits
  resources :latest_dates
  resources :factsheets
  resources :stocks
  resources :sales
  resources :statistics  
  resources :charts, only: [] do
  collection do
    get 'stocks_by_status'
  end
end
  get 'pages/home'

   root 'pages#home'

    get "/list_buy_alert", to: 'sales#list_buy_alert'
    get "/list_sell_alert", to: 'sales#list_sell_alert'
    get "/list_short_sell", to: 'sales#list_short_sell'
    get "/list_cover_buy", to: 'sales#list_cover_buy'
    get "/list_top10_days", to: 'sales#list_top10_days'
    get 'export', to: 'sales#export', as: :sales_export
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><% if content_for?(:title) %>
               <%= yield :title %>
           <% else %>
               Port_Lite
           <% end %>
    </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">Port_Lite</a>
        </div> <!--end navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Sales', sales_path %></li>            
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= 'Alerts' %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Sell Alert', "/list_sell_alert" %></li> 
                <li><%= link_to 'Buy Alert', "/list_buy_alert" %></li>
                <li role="presentation" class="divider"></li> 
                <li><%= link_to 'Short Sell', "/list_short_sell" %></li> 
                <li><%= link_to 'Cover Buy', "/list_cover_buy" %></li>                
              </ul> 
            </li>
            <li><%= link_to 'Profits', profits_path %></li>   
            <li><%= link_to 'Consensus', consensus_path %></li>   

            <li><%= link_to 'Top 10 Days', "/list_top10_days" %></li>             
            <li><%= link_to 'Stocks', stocks_path %></li>
            <li><%= link_to 'Statistics', statistics_path %></li>
            <li><%= link_to 'Date', latest_dates_path %></li>
          </ul>
        </div><!--end of collapse navbar-collapse -->

      </div> <!-- end of container -->
    </nav>  <!-- End of nav element --> 
    <div class="container bodyContent"> <!-- from Bootstrap for Rails -->
      <%= yield %>
    </div> <!-- end of container -->

</body>
</html>